# Generated by Django 4.2.7 on 2023-11-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registros_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_codigo', models.CharField(max_length=10)),
                ('d_asenta', models.CharField(max_length=70)),
                ('d_tipo_asenta', models.CharField(max_length=40)),
                ('D_mnpio', models.CharField(max_length=40)),
                ('d_estado', models.CharField(max_length=40)),
                ('d_ciudad', models.CharField(max_length=40)),
                ('d_CP', models.CharField(max_length=10)),
                ('c_estado', models.CharField(max_length=4)),
                ('c_oficina', models.CharField(max_length=10)),
                ('c_CP', models.CharField(blank=True, max_length=3)),
                ('c_tipo_asenta', models.CharField(max_length=4)),
                ('c_mnpio', models.CharField(max_length=5)),
                ('id_asenta_cpcons', models.CharField(max_length=4)),
                ('d_zona', models.CharField(max_length=25)),
                ('c_cve_ciudad', models.CharField(max_length=5)),
            ],
        ),
    ]
